# Bestway Lay-Z-Spa ESPHome Configuration
# Native ESPHome component - direct serial/SPI protocol communication
#
# Supports both 4-wire (2021+) and 6-wire (pre-2021) Bestway spa models
# Based on VisualApproach hardware design and protocol documentation
#
# For hardware build instructions, see: https://github.com/visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA

substitutions:
  device_name: bestway-spa
  friendly_name: "Hot Tub"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: "Bestway Lay-Z-Spa Controller"

esp8266:
  board: nodemcuv2  # NodeMCU v2/v3 ESP8266

# Enable logging (disable serial logging since UART is used for spa)
logger:
  level: DEBUG
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable OTA updates
ota:
  - platform: esphome
    password: !secret ota_password

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret fallback_password

# Web server for debugging
web_server:
  port: 80

# =============================================================================
# UART Configuration (used for both 4-wire UART and 6-wire CS/timing)
# =============================================================================
uart:
  id: spa_uart
  tx_pin: GPIO1   # D10/TX on NodeMCU
  rx_pin: GPIO3   # D9/RX on NodeMCU
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

# =============================================================================
# Custom Component
# =============================================================================
# Option 1: Use GitHub repository (recommended for most users)
external_components:
  - source:
      type: git
      url: https://github.com/tsquared96/ESPHome-Bestway-LazySpa
      ref: aa10201fcb952865d6e066fbbf513e0a10dc793d
    components: [ bestway_spa ]

# Option 2: Use local path (if you cloned the repo locally)
# external_components:
#   - source:
#       type: local
#       path: /config/esphome/ESPHome-Bestway-LazySpa/components
#     components: [ bestway_spa ]

# =============================================================================
# CLIMATE CONFIGURATION
# =============================================================================
#
# Protocol options:
#   4WIRE      - 2021+ models using UART (most common)
#   6WIRE      - Pre-2021 models using SPI-like protocol (TYPE1)
#   6WIRE_T1   - Same as 6WIRE (TYPE1)
#   6WIRE_T2   - 6-wire TYPE2 (54149E model)
#
# Model options (affects button codes and features):
#   PRE2021    - Pre-2021 6-wire model (TYPE1)
#   P05504     - 6-wire TYPE1 variant
#   54149E     - 6-wire TYPE2 model
#   54123      - 4-wire, no jets, no air
#   54138      - 4-wire with jets and air
#   54144      - 4-wire with jets
#   54154      - 4-wire basic (default)
#   54173      - 4-wire with jets and air
#
# =============================================================================

climate:
  - platform: bestway_spa
    id: hot_tub
    name: "${friendly_name}"
    uart_id: spa_uart

    # =========================================================================
    # PROTOCOL CONFIGURATION - Choose ONE of these configurations:
    # =========================================================================

    # --- Option A: 4-Wire UART (2021+ models) ---
    # protocol_type: 4WIRE
    # model: "54154"

    # --- Option B: 6-Wire TYPE1 (Pre-2021 models) ---
    # MITM dual-bus architecture - separate CIO input and DSP output buses
    protocol_type: 6WIRE
    model: PRE2021
    # CIO bus (input from pump controller)
    cio_clk_pin: GPIO4    # D2 - Clock from CIO
    cio_data_pin: GPIO5   # D1 - Data from CIO (input)
    cio_cs_pin: GPIO14    # D5 - Chip Select from CIO
    # DSP bus (output to pump controller)
    dsp_data_pin: GPIO12  # D6 - Data to CIO (output for button codes)
    audio_pin: GPIO13     # D7 - Audio/Buzzer (optional)

    # --- Option C: 6-Wire TYPE2 (54149E model) ---
    # protocol_type: 6WIRE_T2
    # model: 54149E
    # clk_pin: GPIO14
    # data_pin: GPIO12
    # cs_pin: GPIO13
    # audio_pin: GPIO15

    # =========================================================================
    # SENSORS
    # =========================================================================

    # Temperature sensors
    current_temperature:
      name: "${friendly_name} Current Temperature"
      filters:
        - sliding_window_moving_average:
            window_size: 3
            send_every: 1

    target_temperature:
      name: "${friendly_name} Target Temperature"

    # Binary sensors for state monitoring
    heating:
      name: "${friendly_name} Heating"
      device_class: heat

    filter:
      name: "${friendly_name} Filter Running"
      device_class: running

    bubbles:
      name: "${friendly_name} Bubbles"
      device_class: running

    jets:
      name: "${friendly_name} Jets"
      device_class: running

    power:
      name: "${friendly_name} Power"
      device_class: power

    locked:
      name: "${friendly_name} Child Lock"
      device_class: lock

    error:
      name: "${friendly_name} Error"
      device_class: problem

    # Text sensors
    error_text:
      name: "${friendly_name} Error Code"

    display_text:
      name: "${friendly_name} Display"

    button_status:
      name: "${friendly_name} Button Status"

# =============================================================================
# CONTROL SWITCHES
# =============================================================================

switch:
  - platform: bestway_spa
    type: power
    name: "${friendly_name} Power"
    icon: mdi:power
    bestway_spa_id: hot_tub

  - platform: bestway_spa
    type: heater
    name: "${friendly_name} Heater"
    icon: mdi:radiator
    bestway_spa_id: hot_tub

  - platform: bestway_spa
    type: filter
    name: "${friendly_name} Filter Pump"
    icon: mdi:air-filter
    bestway_spa_id: hot_tub

  - platform: bestway_spa
    type: bubbles
    name: "${friendly_name} Air Bubbles"
    icon: mdi:chart-bubble
    bestway_spa_id: hot_tub

  - platform: bestway_spa
    type: jets
    name: "${friendly_name} Jets"
    icon: mdi:waves
    bestway_spa_id: hot_tub

  - platform: bestway_spa
    type: lock
    name: "${friendly_name} Child Lock"
    icon: mdi:lock
    bestway_spa_id: hot_tub

  - platform: bestway_spa
    type: unit
    name: "${friendly_name} Celsius"
    icon: mdi:thermometer
    bestway_spa_id: hot_tub

  - platform: bestway_spa
    type: timer
    name: "${friendly_name} Timer"
    icon: mdi:timer
    bestway_spa_id: hot_tub

  - platform: bestway_spa
    type: up
    name: "${friendly_name} Temp Up"
    icon: mdi:arrow-up-bold
    bestway_spa_id: hot_tub

  - platform: bestway_spa
    type: down
    name: "${friendly_name} Temp Down"
    icon: mdi:arrow-down-bold
    bestway_spa_id: hot_tub

# =============================================================================
# SYSTEM SENSORS
# =============================================================================

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "${friendly_name} Uptime"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
    ssid:
      name: "${friendly_name} SSID"

# =============================================================================
# STATUS LED
# =============================================================================

status_led:
  pin:
    number: GPIO2
    inverted: true
