# =============================================================================
# Bestway Spa ESPHome Configuration - PRE2021 / P05504 Models
# =============================================================================
# For 6-wire TYPE1 protocol spas (pre-2021 "egg-style" pump models)
#
# Hardware: ESP8266 D1 Mini with VisualApproach MITM board
#
# Pin Configuration (matching VA firmware defaults):
#   CIO Bus (from pump controller):
#     - GPIO5  (D1) = CIO Data
#     - GPIO4  (D2) = CIO Clock
#     - GPIO14 (D5) = CIO Chip Select
#   DSP Bus (to physical display):
#     - GPIO12 (D6) = DSP Data
#     - GPIO2  (D4) = DSP Clock
#     - GPIO0  (D3) = DSP Chip Select
# =============================================================================

substitutions:
  device_name: bestway-spa
  friendly_name: "Bestway Spa"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp8266:
  board: d1_mini

logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${device_name}-fallback"
    password: !secret ap_password

captive_portal:

web_server:
  port: 80

# External component source
external_components:
  - source:
      type: git
      url: https://github.com/tsquared96/ESPHome-Bestway-LazySpa
      ref: gemini-edits
    components: [bestway_spa]

# =============================================================================
# Climate Platform - Main spa control
# =============================================================================
climate:
  - platform: bestway_spa
    id: spa
    name: "${friendly_name}"
    protocol_type: 6WIRE_T1

    # CIO bus pins (input from pump controller)
    cio_data_pin: GPIO5
    cio_clk_pin: GPIO4
    cio_cs_pin: GPIO14

    # DSP bus pins (output to physical display)
    dsp_data_pin: GPIO12
    dsp_clk_pin: GPIO2
    dsp_cs_pin: GPIO0

# =============================================================================
# Temperature Sensors
# =============================================================================
sensor:
  - platform: bestway_spa
    bestway_spa_id: spa
    current_temperature:
      name: "${friendly_name} Current Temperature"
    target_temperature:
      name: "${friendly_name} Target Temperature"

# =============================================================================
# Binary Sensors - State monitoring
# =============================================================================
binary_sensor:
  - platform: bestway_spa
    bestway_spa_id: spa
    heating_sensor:
      name: "${friendly_name} Heating"
    filter_sensor:
      name: "${friendly_name} Filter Pump"
    bubbles_sensor:
      name: "${friendly_name} Bubbles"

# =============================================================================
# Text Sensors
# =============================================================================
text_sensor:
  - platform: bestway_spa
    bestway_spa_id: spa
    display_text:
      name: "${friendly_name} Display"

# =============================================================================
# Manual Button Controls (using lambdas)
# =============================================================================
button:
  - platform: template
    name: "${friendly_name} Bubbles Toggle"
    on_press:
      - lambda: 'id(spa).on_button_press_(esphome::bestway_spa::BUBBLES);'

  - platform: template
    name: "${friendly_name} Pump Toggle"
    on_press:
      - lambda: 'id(spa).on_button_press_(esphome::bestway_spa::PUMP);'

  - platform: template
    name: "${friendly_name} Heat Toggle"
    on_press:
      - lambda: 'id(spa).on_button_press_(esphome::bestway_spa::HEAT);'

  - platform: template
    name: "${friendly_name} Lock Toggle"
    on_press:
      - lambda: 'id(spa).on_button_press_(esphome::bestway_spa::LOCK);'

  - platform: restart
    name: "${friendly_name} Restart"
