# =============================================================================
# Bestway Spa ESPHome Configuration - PRE2021 / P05504 Models
# =============================================================================
# For 6-wire TYPE1 protocol spas (pre-2021 models)
#
# Hardware: ESP8266 D1 Mini with VisualApproach MITM board
#
# Pin Configuration (per VA documentation):
#   CIO Bus (from pump controller):
#     - GPIO13 (D7) = CIO Data
#     - GPIO4  (D2) = CIO Clock
#     - GPIO5  (D1) = CIO Chip Select
#   DSP Bus (to physical display):
#     - GPIO14 (D5) = DSP Data
#     - GPIO2  (D4) = DSP Clock
#     - GPIO0  (D3) = DSP Chip Select
#     - GPIO12 (D6) = DSP Audio (optional)
# =============================================================================

substitutions:
  device_name: bestway-spa
  friendly_name: "Bestway Spa"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${device_name}-fallback"
    password: !secret ap_password

captive_portal:

# Web server for local access
web_server:
  port: 80

# Bestway Spa component - PRE2021 6-wire TYPE1
external_components:
  - source:
      type: local
      path: components

climate:
  - platform: bestway_spa
    id: spa
    name: "${friendly_name}"

    # Model configuration - PRE2021 uses 6-wire TYPE1 protocol
    protocol_type: 6WIRE
    model: PRE2021

    # CIO bus pins (input from pump controller)
    cio_data_pin: GPIO13   # D7
    cio_clk_pin: GPIO4     # D2
    cio_cs_pin: GPIO5      # D1

    # DSP bus pins (output to physical display)
    dsp_data_pin: GPIO14   # D5
    dsp_clk_pin: GPIO2     # D4
    dsp_cs_pin: GPIO0      # D3
    audio_pin: GPIO12      # D6 (optional - for buzzer)

    # Sensors
    current_temperature:
      name: "${friendly_name} Current Temperature"

    # Binary sensors for state monitoring
    heating:
      name: "${friendly_name} Heating"
    filter:
      name: "${friendly_name} Filter Pump"
    bubbles:
      name: "${friendly_name} Bubbles"
    locked:
      name: "${friendly_name} Locked"
    power:
      name: "${friendly_name} Power"
    error:
      name: "${friendly_name} Error"

    # Text sensors
    error_text:
      name: "${friendly_name} Error Code"
    display_text:
      name: "${friendly_name} Display"

# Control switches
switch:
  - platform: bestway_spa
    spa_id: spa
    heater:
      name: "${friendly_name} Heater"
    filter:
      name: "${friendly_name} Filter"
    bubbles:
      name: "${friendly_name} Air Jets"
    lock:
      name: "${friendly_name} Lock"
    power:
      name: "${friendly_name} Power"
    unit:
      name: "${friendly_name} Unit (C/F)"

# Restart button
button:
  - platform: restart
    name: "${friendly_name} Restart"
