# Bestway Lay-Z-Spa ESPHome Configuration
# Direct serial communication - replaces Visualapproach firmware entirely
#
# Uses existing Visualapproach hardware (PCB with level shifters)

substitutions:
  device_name: bestway-spa
  friendly_name: "Hot Tub"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: "Bestway Lay-Z-Spa Controller"

esp8266:
  board: nodemcuv2  # Match your Visualapproach hardware

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0  # Disable serial logging since UART is used for spa

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key

# Enable OTA
ota:
  - platform: esphome
    password: !secret ota_password

# WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret fallback_password

# Web server for debugging
web_server:
  port: 80

# UART configuration for spa communication
uart:
  id: spa_uart
  tx_pin: GPIO1   # D10/TX on NodeMCU
  rx_pin: GPIO3   # D9/RX on NodeMCU
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

# Custom component
external_components:
  - source:
      type: local
      path: components
    components: [ bestway_spa ]

# Main climate control with full sensors
climate:
  - platform: bestway_spa
    id: hot_tub
    name: "${friendly_name}"
    uart_id: spa_uart
    protocol_type: 4WIRE  # Use "6WIRE" for pre-2021 models
    
    # Temperature sensors
    current_temperature:
      name: "${friendly_name} Current Temperature"
      filters:
        - sliding_window_moving_average:
            window_size: 3
            send_every: 1
    
    target_temperature:
      name: "${friendly_name} Target Temperature"
    
    # Binary sensors
    heating:
      name: "${friendly_name} Heating"
      device_class: heat
    
    filter:
      name: "${friendly_name} Filter Running"
      device_class: running
    
    bubbles:
      name: "${friendly_name} Bubbles Running"
      device_class: running
    
    locked:
      name: "${friendly_name} Child Lock"
      device_class: lock
    
    error:
      name: "${friendly_name} Error"
      device_class: problem
    
    # Error code text
    error_text:
      name: "${friendly_name} Error Code"

# Control switches
switch:
  - platform: bestway_spa_heater
    name: "${friendly_name} Heater"
    icon: mdi:radiator
    bestway_spa_id: hot_tub
  
  - platform: bestway_spa_filter
    name: "${friendly_name} Filter Pump"
    icon: mdi:air-filter
    bestway_spa_id: hot_tub
  
  - platform: bestway_spa_bubbles
    name: "${friendly_name} Air Bubbles"
    icon: mdi:chart-bubble
    bestway_spa_id: hot_tub
  
  - platform: bestway_spa_lock
    name: "${friendly_name} Child Lock"
    icon: mdi:lock
    bestway_spa_id: hot_tub

# System sensors
sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
  
  - platform: uptime
    name: "${friendly_name} Uptime"

# WiFi info
text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
    ssid:
      name: "${friendly_name} SSID"

# Status LED (built-in)
status_led:
  pin:
    number: GPIO2
    inverted: true
